name: clock
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  flutter_hooks: ^0.14.0
  hooks_riverpod: ^0.10.1
  cupertino_icons: ^0.1.3
  google_fonts: ^1.1.0 # it helps us to use google fonts on our app
  flutter_svg: ^0.18.0 # it helps us to use SVG in our app

dev_dependencies:

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
